name: Reusable Terraform CI

on:
  workflow_call:
    inputs:
      path:
        type: string
        required: false
        default: '.'
      vars-file:
        type: string
        required: true
      backend-config-file:
        type: string
        required: false
        default: 'default'
      workspace:
        type: string
        required: false
        default: 'default'
      role-to-assume:
        type: string
        required: true
      terraform-version:
        type: string
        required: false
        default: 'latest'
      gh-token:
        type: string
        required: false
        default: 'notoken'

jobs:
  terraform-ci:
    runs-on: vtv-runner-set-id
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup AWS CLI
        uses: CelfocusProduct-VTV/setup-aws-cli@v1

      - name: Set up Github Token
        if: ${{ inputs.gh-token != 'notoken' }}
        shell: bash
        run: |
          git config --global url."https://oauth2:${{ inputs.gh-token }}@github.com".insteadOf "https://github.com"

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ inputs.role-to-assume }}

      - name: Terraform fmt check
        run: terraform fmt -recursive -diff -check
        working-directory: ${{ inputs.path }}
        shell: bash

      - name: Terraform Init (default)
        if: ${{ inputs.backend-config-file == 'default' }}
        run: terraform init
        working-directory: ${{ inputs.path }}
        shell: bash

      - name: Terraform Init
        if: ${{ inputs.backend-config-file != 'default' }}
        run: terraform init --backend-config=${{ inputs.backend-config-file }}
        working-directory: ${{ inputs.path }}
        shell: bash

      - name: Terraform workspace select
        run: terraform workspace select -or-create ${{ inputs.workspace }}
        working-directory: ${{ inputs.path }}
        shell: bash

      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: ${{ inputs.path }}
        shell: bash

      - name: Terraform plan
        run: terraform plan -var-file=${{ inputs.vars-file }}
        working-directory: ${{ inputs.path }}
        shell: bash
